import{S as d,i as c}from"./assets/vendor-5b791d57.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const m=document.querySelector(".form"),a=document.querySelector(".gallery-grid"),l=document.querySelector(".loader");let f=new d(".gallery-grid a",{captionsData:"alt"});const y="https://pixabay.com/api/";m.addEventListener("submit",g);function g(s){s.preventDefault();const i=s.target.elements.query.value.trim();if(!i){a.innerHTML="",c.error({message:"Search field is empty",position:"topRight"});return}l.style.display="inline-block",h(i).then(t=>{var o;if(((o=t==null?void 0:t.hits)==null?void 0:o.length)>0){l.style.display="none",b(t.hits);return}throw Error("Sorry, there are no images matching your search query. Please try again!")}).catch(t=>{c.info({message:typeof t=="string"?t:"Something went wrong, sorry!",position:"topRight"})}),s.target.reset()}function h(s){const t=`?${new URLSearchParams({key:"42157668-d969611c6fdd34526589fe987",q:s,image_type:"photo",orientation:"horizontal",safeSearch:!0})}`,o=y+t;return l.style.display="inline-block",fetch(o).then(e=>e.json())}function b(s){a.innerHTML="";const i=s.map(({webformatURL:t,largeImageURL:o,tags:e,likes:r,views:n,comments:u,downloads:p})=>`<a href="${o}" class="gallery-card">
      <img src="${t}" alt="${e}" >
      <div class="img-details-box">
      <p class="detail-item"><b>Likes:</b> ${r}</p>
      <p class="detail-item"><b>Views:</b> ${n}</p>
      <p class="detail-item"><b>Comments:</b> ${u}</p>
      <p class="detail-item"><b>Downloads:</b> ${p}</p></div>
      </a>`).join("");a.insertAdjacentHTML("beforeend",i),f.refresh()}
//# sourceMappingURL=commonHelpers.js.map
