import{i as a,S as f}from"./assets/vendor-5b791d57.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const p=document.querySelector(".form"),c=document.querySelector(".gallery-grid"),d="https://pixabay.com/api/";p.addEventListener("submit",g);function g(s){s.preventDefault();const i=s.target.elements.query.value.trim();if(!i){a.error({message:"Search field is empty",position:"topRight"});return}y(i).then(r=>{var o;if(((o=r==null?void 0:r.hits)==null?void 0:o.length)>0){h(r.hits);return}throw Error("Sorry, there are no images matching your search query. Please try again!")}).catch(r=>{a.info({message:typeof r=="string"?r:"Something went wrong, sorry!",position:"topRight"})}),s.target.reset()}function y(s){const r=`?${new URLSearchParams({key:"42157668-d969611c6fdd34526589fe987",q:s,image_type:"photo",orientation:"horizontal",safeSearch:!0})}`,o=d+r;return fetch(o).then(e=>e.json())}function h(s){c.innerHTML="";const i=s.map(({webformatURL:o,largeImageURL:e,tags:t,likes:n,views:l,comments:u,downloads:m})=>`<a href="${e}" class="gallery-card">
      <img src="${o}" alt="${t}" >
      <div class="img-details-box">
      <p class="detail-item"><b>Likes:</b> ${n}</p>
      <p class="detail-item"><b>Views:</b> ${l}</p>
      <p class="detail-item"><b>Comments:</b> ${u}}</p>
      <p class="detail-item"><b>Downloads:</b> ${m}</p></div>
      </a>`).join("");c.insertAdjacentHTML("beforeend",i),new f(".gallery-grid a",{captionsData:"alt"}).refresh()}
//# sourceMappingURL=commonHelpers.js.map
